version: '2'

volumes:
  postgres-data-volume:
  openldap-ldap-volume:
  openldap-slapd.d-volume:
  jira-data-volume:
  jira-logs-volume:
  jenkins-data-volume:
  sonarqube-data-volume:
  sonarqube-extensions-volume:
  sonarqube-config-volume:

services:
  postgresql:
    build: bdd
    restart: always
    volumes:
      - postgres-data-volume:/var/lib/postgresql/data

  openldap:
    image: "osixia/openldap"
    restart: always
    volumes:
      - openldap-ldap-volume:/var/lib/ldap
      - openldap-slapd.d-volume:/etc/ldap/slapd.d
    environment:
      - LDAP_ORGANISATION=${OPENLDAP_ORGANISATION}
      - LDAP_DOMAIN=${OPENLDAP_DOMAIN}
      - LDAP_ADMIN_PASSWORD=${OPENLDAP_ADMIN_PASSWORD}

  jira:
    image: "blacklabelops/jira"
    restart: always
    volumes:
      - jira-data-volume:/var/atlassian/jira
      - jira-logs-volume:/opt/atlassian/jira/logs
    links:
      - postgresql:postgresql
      - openldap:openldap
    ports:
      - "${JIRA_PORT}:8080"
    environment:
      - JIRA_DATABASE_URL=postgresql://${JIRA_USR}@postgresql/${JIRA_DB}
      - JIRA_DB_PASSWORD=${JIRA_PWD}


  jenkins:
    image: "jenkinsci/jenkins"
    restart: always
    volumes:
      - jenkins-data-volume:/var/jenkins_home
    ports:
      - "${JENKINS_PORT}:8080"
      - "50000:50000"

  sonarqube:
    image: "sonarqube"
    restart: always
    volumes:
      - sonarqube-data-volume:/opt/sonarqube/data
      - sonarqube-extensions-volume:/opt/sonarqube/extensions
      - sonarqube-config-volume:/opt/sonarqube/config
    ports:
      -  "${SONAR_PORT}:9000"
    links:
      - postgresql:postgresql
      - openldap:openldap
    depends_on:
      - postgresql
      - openldap
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgresql:5432/${SONAR_DB}
      - SONARQUBE_JDBC_USERNAME=${SONAR_USR}
      - SONARQUBE_JDBC_PASSWORD=${SONAR_PWD}
